### ISSUE TITLE
Dodaj #general zjebko

### ISSUE THREAD

**Issue by Muffinaa** [Korrumz2PL/skyndalex-public#30]
dodaj kanal tekstowy spowrotem miernoto

**Comment by Korrumz2PL** [comment]
![image](https://user-images.githubusercontent.com/55253305/167255927-c6c0e6da-dc91-4df0-bbe4-bf1d7199e5f8.png)

**Comment by Korrumz2PL** [comment]
chcesz????

**Comment by HarnesHa12** [comment]
Czlowieku kanał tylko chce on

**Comment by Muffinaa** [comment]
typowy 8 klasista be like

**Comment by Korrumz2PL** [comment]
Zastanowie sie

> Czlowieku kanał tylko chce onnowie sie

**Comment by Korrumz2PL** [comment]
Jak zrobie automoda to moze ok

**Comment by Muffinaa** [comment]
ta z blacklistujesz wszystkie słowa którymi moglibyśmy ciebie urazic

**Comment by Korrumz2PL** [comment]
ten serwer nie służy do jechania po ludziach więc pomyślę nad czymś co będzie blokować ogólnie toksyczność.

**Comment by Muffinaa** [comment]
wydaje mi się że kiedyś mówiłeś że masz wyjebane co ludzie o tobie myśla a jednak usuwasz kanał jak ciebie zartujemy

**Comment by Korrumz2PL** [comment]
aktualnie pracuje nad innymi rzeczami (np. system embedów, trello manager), które chcę najpierw skończyć

**Comment by Korrumz2PL** [comment]
> wydaje mi się że kiedyś mówiłeś że masz wyjebane co ludzie o tobie myśla a jednak usuwasz kanał jak ciebie zartujemy

owszem mam wywalone, aczkolwiek obawiałbym się co do nowych osób.

**Comment by Korrumz2PL** [comment]
myślę ze można zamknąć

**Comment by MinerPL** [comment]
Xd

**Comment by adasiek193** [comment]
XD

**Comment by Korrumz2PL** [comment]
co was tak śmieszy halo

**Comment by Korrumz2PL** [comment]
chyba że chcecie żeby na dc się wyświetlało

**Comment by MinerPL** [comment]
ty, a co?

**Comment by Korrumz2PL** [comment]
mam na myśli konkretną czynność którą robię

**Comment by MinerPL** [comment]
To co w tym issue napisałeś.

**Comment by Korrumz2PL** [comment]
Zacytuj

**Comment by Korrumz2PL** [comment]
test

**Comment by Korrumz2PL** [comment]
test2

**Comment by Korrumz2PL** [comment]
test223

**Comment by Korrumz2PL** [comment]
testestesttes

**Comment by Korrumz2PL** [comment]
ttt

**Comment by Korrumz2PL** [comment]
testtest

**Comment by jelni** [comment]
co tu się dzieje

**Comment by Korrumz2PL** [comment]
nic nic
