### ISSUE TITLE
frajerko dodaj general

### ISSUE THREAD

**Issue by Muffinaa** [Korrumz2PL/skyndalex-public#31]
chuja mnie twoja moederacja jak sie splaczes to po prostu z timeoutuj kogos a nie usuwasz kanal jak baba bo cisniemy z ciebie beke tez chcemy popisac szmaciuro

**Comment by Muffinaa** [comment]
siusisiaczku dawaj permisje

**Comment by Muffinaa** [comment]
bo jak nie

**Comment by Muffinaa** [comment]
to ogarne twoje ip i będzie szlaban

**Comment by Muffinaa** [comment]
na robienie bocikow

**Comment by Muffinaa** [comment]
nie zartuje

**Comment by Muffinaa** [comment]
twoje ip miernoto 127.0.0.1

**Comment by Muffinaa** [comment]
dohra wylaczam ci neta na miesiac koniec smieszkowania

**Comment by Muffinaa** [comment]
i co juz lagujesz

**Comment by Korrumz2PL** [comment]
przygladam sie tylko bo moje ip to tak naprawde localhost

**Comment by Muffinaa** [comment]
haha izi 500

**Comment by Muffinaa** [comment]
szmaro oddawaj kanal

**Comment by Muffinaa** [comment]
bo cię wycweluje na amen

**Comment by Muffinaa** [comment]
przez twoje dupsko pociągi będą mogly jechac jak z tobą skoncze

**Comment by Muffinaa** [comment]
penetracja jak rakieta

**Comment by Korrumz2PL** [comment]
nie mam dupska

**Comment by Korrumz2PL** [comment]
łatwo

**Comment by Muffinaa** [comment]
to wezme kurwa wiertarke

**Comment by Korrumz2PL** [comment]
jestem wiertarkoodporny

**Comment by Muffinaa** [comment]
i będziesz mial

**Comment by wnm210** [comment]
widze ze kanal <#963878263825006632> sie od dzis zmienil w kanal chat

**Comment by Muffinaa** [comment]
skoro tak

**Comment by Muffinaa** [comment]
to jebac korumzza

**Comment by Korrumz2PL** [comment]
> Author

![image](https://user-images.githubusercontent.com/55253305/167501303-75ee515a-ecdb-4999-bbfd-9bbe4d1e08f1.png)
zawsze jest opcja

**Comment by wnm210** [comment]
psujesz kontent

**Comment by Muffinaa** [comment]
> > Author
> 
> ![image](https://user-images.githubusercontent.com/55253305/167501303-75ee515a-ecdb-4999-bbfd-9bbe4d1e08f1.png)
> zawsze jest opcja

zrób to a nie masz wacka

**Comment by Muffinaa** [comment]
odetne ci go szmato

**Comment by Muffinaa** [comment]
zębami

**Comment by Korrumz2PL** [comment]
> 

nie no nie zrobie tego, tez mi chumor robi

> psujesz kontent

**Comment by wnm210** [comment]
ratio

**Comment by Korrumz2PL** [comment]
> odetne ci go szmato

don't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur momdon't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur momdon't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur momdon't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowall

**Comment by Muffinaa** [comment]
ratio

**Comment by Muffinaa** [comment]
don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + h0es mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your’re probably white + ratio don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + h0es mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your’re probably white + not funny didn’t laugh + you’re* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur momdon’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your’re a full time discordian + not funny didn’t laugh + you’re* + grammar issue + go outside + get good + your gay + reported + ad hominem + GG! + ur mom + unknown + random + biased + racially motivated + kys + ur unfunny +ratio don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + h0es mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + I'm illegal shut up with yo oh Lord Farquad ass bitch R2D2 speaking ass hoe, built like the monster hercules killed damn three headed snaked ass faggot. you're the reason faggots have no right little ass bitch. Zooophile, orlin from Nikocado ass bitch. Looking like Rihannas big ass forhead and Dwayne Johnsons bald headed ass had an abortion. Environmental scientists had to consider you endagered cause no fucking person in the entire universe would breed with your shrek in human form looking ass,

**Comment by Korrumz2PL** [comment]
Plot twist: mam dynamiczne IP

**Comment by Muffinaa** [comment]
plot twist: nie pytalem

**Comment by Muffinaa** [comment]
tworz nowy kanal chat

**Comment by Korrumz2PL** [comment]
nie chce mi sie

**Comment by Muffinaa** [comment]
oby ci szafa się na matke zwalila

**Comment by Muffinaa** [comment]
plot twist: nie masz jej

**Comment by Muffinaa** [comment]
szafy też

**Comment by Korrumz2PL** [comment]
mam matke w twoim domu

**Comment by Muffinaa** [comment]
poka jej cyce

**Comment by Muffinaa** [comment]
pomizac chcę je

**Comment by Korrumz2PL** [comment]
Chwila, wyjmuje telefon

**Comment by Korrumz2PL** [comment]
https://ujeb.se/VXJHbX

**Comment by wnm210** [comment]
nice one
